#!/bin/bash

function flash_context () {
   flash_context_git && echo "git"
}

function flash_context_git () {
   git branch &>/dev/null
}


function flash_find_git_opts () {
   echo -name '.git' -prune -or 
   echo -name 'venv' -prune -or
   echo -name 'target' -prune -or
   echo -name '*.class' -prune -or
   echo -name 'node_modules' -prune -or
   echo -name 'bower_components' -prune -or
}

function flash_find_context_opts () {
   case $(flash_context) in
      git) flash_find_git_opts;;
   esac
}


function flash_grep_git_opts () {
   echo --exclude-dir=\.git
   echo --exclude-dir=node_modules
   echo --exclude-dir=bower_components
   echo --exclude-dir=\.tox
   echo --exclude-dir=\.tmp
   echo --exclude-dir=env
   echo --exclude-dir=dist
   echo --exclude-dir=venv
   echo --exclude-dir=target
   echo --exclude-dir=log
   echo --exclude=\*\.jar
   echo --exclude=\*\.class
}

function flash_grep_context_opts () {
   case $(flash_context) in
      git) flash_grep_git_opts;;
   esac
}


function flash_find () {
   (( $# != 1 )) && return 1

   find . $(flash_find_context_opts) -iname '*'"$(basename $1)"'*' -print \
      | grep --color=always -i "$1"
}

function flash_find_file () {
   (( $# != 1 )) && return 1

   find . $(flash_find_context_opts) -type f -iname '*'"$(basename $1)"'*' -print \
      | grep --color=always -i "$1"
}

function flash_find_directory () {
   (( $# != 1 && $# != 2 )) && return 1

   local depth_param="-maxdepth 1"
   [ "$1" = "-r" ] && depth_param="" && shift

   find . $(flash_find_context_opts) -type d $depth_param -iname '*'"$(basename $1)"'*' -print \
      | grep --color=always -i "$1"
}

function flash_grep () {
   (( $# != 1 && $# != 2 )) && return 1

   if tty -s; then
      grep --color=always -rinI $(flash_grep_context_opts) "$1" "${2:-.}" | cut -c -$(tput cols) | endcolor
   else
      grep --color=always -iI $(flash_grep_context_opts) "$1" | cut -c -$(tput cols) | endcolor
   fi
}
